function [ParameterStructure,Text] = Spike_Module_ShowSpikeSortingSettings(Sorter,ParameterStructure,ParameterPresent)

if strcmp(Sorter,"Mountainsort 5")  

    if strcmp(ParameterPresent,"ParameterNOTPresent")
        % Original data
        ParameterStructure.MS5 = struct('scheme', '2', ...
                      'detect_threshold', 5.5, ...
                      'detect_sign', -1, ...
                      'detect_time_radius_msec', 0.5, ...
                      'snippet_T1', 20, ...
                      'snippet_T2', 20, ...
                      'npca_per_channel', 3, ...
                      'npca_per_subdivision', 10, ...
                      'snippet_mask_radius', 250, ...
                      'scheme1_detect_channel_radius', 150, ...
                      'scheme2_phase1_detect_channel_radius', 200, ...
                      'scheme2_detect_channel_radius', 50, ...
                      'scheme2_max_num_snippets_per_training_batch', 200, ...
                      'scheme2_training_duration_sec', 300, ...
                      'scheme2_training_recording_sampling_mode', 'uniform', ...
                      'scheme3_block_duration_sec', 1800, ...
                      'freq_min', 300, ...
                      'freq_max', 6000, ...
                      'filter', false, ...
                      'whiten', true, ...
                      'delete_temporary_recording', true, ...
                      'n_jobs', 4, ...
                      'chunk_duration', '1s', ...
                      'progress_bar', true, ...
                      'mp_context', 'None', ...
                      'max_threads_per_process', 1);
    end
    
    [Text] = Spike_Module_ConverStrucToTextArea(ParameterStructure.MS5,Sorter);

elseif strcmp(Sorter,"SpykingCircus 2") 

    if strcmp(ParameterPresent,"ParameterNOTPresent")
    ParameterStructure.SC2 = struct('general', struct('ms_before', 2, ...
                                        'ms_after', 2, ...
                                        'radius_um', 100), ...
                      'sparsity', struct('method', 'snr', ...
                                         'amplitude_mode', 'peak_to_peak', ...
                                         'threshold', 0.25), ...
                      'filtering', struct('freq_min', 150, ...
                                          'freq_max', 7000, ...
                                          'ftype', 'bessel', ...
                                          'filter_order', 2), ...
                      'detection', struct('peak_sign', 'neg', ...
                                          'detect_threshold', 5), ...
                      'selection', struct('method', 'uniform', ...
                                          'n_peaks_per_channel', 5000, ...
                                          'min_n_peaks', 100000, ...
                                          'select_per_channel', false, ...
                                          'seed', 42), ...
                      'apply_motion_correction', true, ...
                      'motion_correction', struct('preset', 'nonrigid_fast_and_accurate'), ...
                      'merging', struct('similarity_kwargs', struct('method', 'cosine', ...
                                                                    'support', 'union', ...
                                                                    'max_lag_ms', 0.2), ...
                                        'correlograms_kwargs', struct(), ...
                                        'auto_merge', struct('min_spikes', 10, ...
                                                             'corr_diff_thresh', 0.25)), ...
                      'clustering', struct('legacy', true), ...
                      'matching', struct('method', 'wobble'), ...
                      'apply_preprocessing', true, ...
                      'matched_filtering', true, ...
                      'cache_preprocessing', struct('mode', 'memory', ...
                                                     'memory_limit', 0.5, ...
                                                     'delete_cache', true), ...
                      'multi_units_only', false, ...
                      'job_kwargs', struct('n_jobs', 0.8), ...
                      'debug', false);
    end
    
    [Text] = Spike_Module_ConverStrucToTextArea(ParameterStructure.SC2,Sorter);

    Text = split(Text, '\n');
end